### PR TITLE
Chore: Apply some code optimizations for the site

### PR DESCRIPTION
**Pull request by jonniebigodes**
With this pr i updated the code base of your site to make it more simpler to read and understand and more efficient. Removing some issues.

Below is a list of changes that was done to the code:

- added prop-types to package.json
- components/About
  updated imports to better readability /performance
  tranformed into functional component no need to use classes on it.

- components/ArticleContent
  removed the unecessary import for component
  updated the variable assignment cover and subtitle to be destructured, you don't need to create another variable and add it
  styles import to the bottom
  Changed the logic to make the component more simpler to read and understand
  Removed the unecessary var ( as you shouldn't used them currently)

- components/Footer
Same logic that was used in the response to the issue in the Gatsby repo (2 components were created)

- components/PostListing
Updated the imports for better performance
Component is now fully functional
Removed string concatenation to string templates [see more here[(https://flaviocopes.com/javascript-template-literals/) as you shouldn't use them as they could lead to issues.
Removed the need of two array iterations for better performance
Removed the unique key warning by adding a index based key to each element that will be shown( for now it will work, but you should consider some sort of unique id, for instance add the id generated by gatsby to the query that feeds into this component).

- components/PostTags
Turned the component into a functional component to make it more leaner and simpler

- components/ShowCase
Rearranged the imports (css /assets should be at the bottom)

- components/ShowCaseContent
 Rearranged the imports
 Removed the var(you shouldn't use vars as of some time ago).
 Changed the component to render conditionally based on a ternary operator

- components/SocialLinks
Updated the component to a fully functional one, removing the excess functions

- components/UserInfo
Updated the component to become a functional component making it more leaner and simpler to read. 

- components/UserLinks
Updated the imports
Turned it into a simple functional component
The font awsome icons markdown was updated to become self-closing, as they don't have any children they should be so.

- components/Layout
 Updated the imports
 Turned into a functional component to avoid adding unecessary boilerplate
 destructured the showcaseContent, children 

- pages/index
 Was turned into a functional component
 biocomponent islink prop was modified as you don't need to explicitly pass a true value

- pages/about
 Was turned into a functional component

- pages/ranchpage
 was commented out and only shows a h1 element to allow it to build. This needs to be updated

### CODE REVIEW

**Comment by NicoGim** [comment]
Hello.
My apologizes for the late response. I was travelling.
Wow it's really amazing that you took so much time to clean up my mess.
I merge your pull-request asap.

**Comment by jonniebigodes** [comment]
@NicoGim no problem whatsoever, i hope you had a nice trip and no need to apologize and no thanks are in order, just glad that i managed to get you a more "tangible" code base for you to work on, I think i mentioned in the gatsby issue that i was going to make a pr to your repo. I really hope that you get this fixed and soon add the content to the Gatsby showcase. 👍

**Comment by jonniebigodes** [comment]
@NicoGim no problem whatsoever. This pr technically wasn't meant to be merged as is. It was just to show the changes you could do to fix your issue. 

Regarding this:

> You commented out the ranch-under-the-hood.jsx files - which is not desired.

Yes, yes i did...For some reason i wasn't able to get a development build with those files. Probably something that i overlooked. But in order for me to get a clearer picture of what was happening and try and solve your issue i decided it would be best to leave them out. 

Once again, glad that i was able to help you out. Feel free to close this pr and delete the branch when you're able.

**Comment by NicoGim** [comment]
Yes, you were right not to bother with that asciidoc file. It's perfect then, I'll use your suggestions to improve the code in further commits.

Thanks again for your time and efforts, looking forward to working with you again in the future.

**Comment by NicoGim** [comment]
Hi @jonniebigodes ! How are you doing? Hope you are happy and safe.
I was thinking I could add your profile in the "thanks" field in the footer of my site, is that ok for you?
Also, I am (finally) gonna adjust with some of your suggestions from this PR - I'll tag you ;o.

Cheers,
Nicolas

**Comment by jonniebigodes** [comment]
Hey @nicobao i'm doing good and thank you for asking. I hope that you and your loved ones are doing good aswell. And regarding your question, i have no issues whatsoever, feel free to do it. Glad that you're going to go start working on the adjustments and can't wait for checking out the final iteration of the site :)

Best regards and stay safe.

João Cardoso (a.k.a jonniebigodes)

**Pull request closed without merging**
